import React, { useCallback, useEffect, useState } from 'react';
import { Check, Download, MessageCircle, Pencil, RefreshCw, Search, X, Ban, Save } from 'lucide-react';
import api from '../../lib/api';
import '../Schemes.css';

export default function AdminChits(){
 const [rows,setRows]=useState([]),[items,setItems]=useState([]),[plans,setPlans]=useState([]),[planPrices,setPlanPrices]=useState({}),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[edit,setEdit]=useState(null),[notice,setNotice]=useState(''),[packingCharge,setPackingCharge]=useState(50),[deliveryCharge,setDeliveryCharge]=useState(40),[savingCharge,setSavingCharge]=useState(false),[savingPlan,setSavingPlan]=useState(null);
 const load=useCallback(async()=>{const [a,b,c,d]=await Promise.all([api.get('/chits/admin/subscriptions',{params:{status:status||undefined,search}}),api.get('/chits/admin/items'),api.get('/chits/admin/settings'),api.get('/chits/admin/plans')]);setRows(a.data);setItems(b.data);setPackingCharge(c.data.packing_charge_rupees);setDeliveryCharge(c.data.delivery_charge_rupees);setPlans(d.data);setPlanPrices(Object.fromEntries(d.data.map(p=>[p.duration,p.monthly_amount_paise/100])))},[status,search]);
 useEffect(()=>{load()},[load]);
 const save=async()=>{await api.put(`/chits/admin/items/${edit.id}`,edit);setEdit(null);load()};
 const refreshKit=async()=>{try{const p=(await api.post('/chits/admin/items/refresh',{apply:false})).data;if(!p.checked)return setNotice('No chit source links configured. Edit each item and add a reference product URL.');if(window.confirm(`Checked ${p.checked} chit items; ${p.ready} ready. Apply valid image/MRP references?`)){const a=(await api.post('/chits/admin/items/refresh',{apply:true})).data;setNotice(`${a.ready} chit items refreshed`);load()}}catch(e){setNotice(e.response?.data?.detail||'Chit refresh failed')}};
 const exportXlsx=async()=>{const r=await api.get('/chits/admin/export.xlsx',{responseType:'blob'});const u=URL.createObjectURL(r.data),a=document.createElement('a');a.href=u;a.download='chit-subscriptions.xlsx';a.click();URL.revokeObjectURL(u)};
 const saveCharges=async()=>{if(!Number.isFinite(Number(packingCharge))||Number(packingCharge)<1)return setNotice('Packing charge must be at least ₹1');if(!Number.isFinite(Number(deliveryCharge))||Number(deliveryCharge)<0)return setNotice('Delivery charge cannot be negative');setSavingCharge(true);try{const {data}=await api.put('/chits/admin/settings',{packing_charge_rupees:Number(packingCharge),delivery_charge_rupees:Number(deliveryCharge)});setPackingCharge(data.packing_charge_rupees);setDeliveryCharge(data.delivery_charge_rupees);setNotice(`Store charges updated: packing ₹${data.packing_charge_rupees}, delivery ₹${data.delivery_charge_rupees}`)}catch(e){setNotice(e.response?.data?.detail||'Unable to update store charges')}finally{setSavingCharge(false)}};
 const savePlanPrice=async duration=>{const amount=Number(planPrices[duration]);if(!Number.isFinite(amount)||amount<1)return setNotice('Monthly chit price must be at least ₹1');setSavingPlan(duration);try{const {data}=await api.put(`/chits/admin/plans/${duration}/price`,{monthly_amount_rupees:amount});setPlanPrices(x=>({...x,[duration]:data.monthly_amount_rupees}));setNotice(`${duration}-month plan updated to ₹${data.monthly_amount_rupees} per month. Existing subscriptions are unchanged.`);await load()}catch(e){setNotice(e.response?.data?.detail||'Unable to update plan price')}finally{setSavingPlan(null)}};
 const decide=async(x,action)=>{const fullyPaid=x.paid_count>=x.chosen_duration;const labels={approve:fullyPaid?'approve this fully paid chit and enable delivery':'approve this application',deny:fullyPaid?'deny this fully paid chit without any refund':'deny this application and refund captured instalments',cancel:'cancel this ongoing subscription and stop future debits','approve-cancellation':'approve customer cancellation and permanently delete the chit records','reject-cancellation':'reject the customer cancellation request and keep the chit active'};if(!window.confirm(`Are you sure you want to ${labels[action]}?`))return;const reason=window.prompt('Admin note/reason (optional):','')??'';try{const {data}=await api.post(`/chits/admin/${x.id}/${action}`,{reason});setNotice(data.message||`${action} completed successfully`);load()}catch(e){const d=e.response?.data?.detail;setNotice(typeof d==='string'?d:'Action failed')}};
 return <div className="admin-chits"><div className="admin-title"><div><h1>Grocery Chits</h1><p>{rows.length} subscription records</p></div><div><button onClick={refreshKit}><RefreshCw/> Refresh Chit Images & MRP</button><button onClick={exportXlsx}><Download/> Export Excel</button></div></div>
 {notice&&<div className="admin-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 <section className="packing-setting"><div><h2>Chit Plan Prices</h2><p>Changes apply only to new subscriptions. Existing customers retain the price accepted when they joined.</p></div><div className="charge-fields">{plans.map(p=><label key={p.duration}>{p.duration}-month plan<div className="packing-input"><span>₹</span><input type="number" min="1" max="100000" step="0.01" value={planPrices[p.duration]??''} onChange={e=>setPlanPrices(x=>({...x,[p.duration]:e.target.value}))}/></div><small>Total ₹{Number((Number(planPrices[p.duration]||0)*p.duration).toFixed(2)).toLocaleString('en-IN')}</small><button onClick={()=>savePlanPrice(p.duration)} disabled={savingPlan===p.duration}><Save/> {savingPlan===p.duration?'Saving…':'Save Price'}</button></label>)}</div></section>
 <section className="packing-setting"><div><h2>Store Charges</h2><p>Packing applies to new chit slots. Delivery applies to normal orders below ₹499. Existing orders and Razorpay quotes retain their original amount.</p></div><div className="charge-fields"><label>Chit packing<div className="packing-input"><span>₹</span><input type="number" min="1" max="10000" step="0.01" value={packingCharge} onChange={e=>setPackingCharge(e.target.value)}/></div></label><label>Normal delivery<div className="packing-input"><span>₹</span><input type="number" min="0" max="10000" step="0.01" value={deliveryCharge} onChange={e=>setDeliveryCharge(e.target.value)}/></div></label><button onClick={saveCharges} disabled={savingCharge}><Save/> {savingCharge?'Saving…':'Save Charges'}</button></div></section>
 <div className="admin-tools"><div className="search"><Search/><input placeholder="Card No or phone" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="pending_admin_approval">Pending Approval</option><option value="refund_failed">Refund Failed / Re-review</option><option value="cancellation_requested">Cancellation Requests</option><option value="due_today">Due Today</option><option value="active">Paid / Active</option><option value="due">Defaulters / Due</option><option value="ready_for_delivery">Ready for Delivery</option><option value="delivery_booked">Delivery Booked</option><option value="cancelled">Cancelled</option><option value="denied">Denied / Refunded</option><option value="denied_no_refund">Denied / No Refund</option></select><button onClick={load}><RefreshCw/> Refresh</button></div>
 <div className="admin-table"><table><thead><tr><th>Card</th><th>Customer</th><th>Plan</th><th>Progress</th><th>Next due</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(x=>{const fullyPaid=x.paid_count>=x.chosen_duration;return <tr key={x.id}><td><b>{x.card_no}</b></td><td>{x.name}<small>{x.phone}</small></td><td>{x.chosen_duration} months</td><td>{x.paid_count}/{x.chosen_duration}</td><td>{x.next_due_date?new Date(x.next_due_date).toLocaleDateString('en-IN'):'—'}</td><td><span className={`status ${x.status}`} title={x.refund_error||''}>{x.status.replaceAll('_',' ')}</span>{x.refund_error&&<small className="refund-error">{x.refund_error}</small>}</td><td><div className="row-actions">{x.status==='pending_admin_approval'&&<><button className="approve" title="Approve" onClick={()=>decide(x,'approve')}><Check/></button><button className="deny" title={fullyPaid?'Deny without refund':'Deny and refund'} onClick={()=>decide(x,'deny')}><X/></button></>}{x.status==='cancellation_requested'&&<><button className="approve" title="Approve cancellation and delete records" onClick={()=>decide(x,'approve-cancellation')}><Check/> Delete</button><button className="deny" title="Reject cancellation" onClick={()=>decide(x,'reject-cancellation')}><X/> Keep</button></>}{x.status==='refund_failed'&&fullyPaid&&<><button className="approve" title="Re-approve and enable delivery" onClick={()=>decide(x,'approve')}><Check/> Re-approve</button><button className="deny" title="Deny without refund" onClick={()=>decide(x,'deny')}><X/> Deny no refund</button></>}{x.status==='refund_failed'&&!fullyPaid&&<button className="deny retry-refund" title="Retry refund and deny" onClick={()=>decide(x,'deny')}><RefreshCw/> Retry refund</button>}{['active','due','ready_for_delivery','authenticated'].includes(x.status)&&<button className="cancel" title="Cancel subscription" onClick={()=>decide(x,'cancel')}><Ban/></button>}<button title="Send WhatsApp reminder" onClick={()=>api.post(`/chits/admin/${x.id}/remind`)}><MessageCircle/></button></div></td></tr>})}</tbody></table></div>
 <section className="master-kit"><h2>Master 40-item kit</h2><p>These quantities represent the complete 12-month entitlement.</p><div className="admin-table"><table><thead><tr><th>#</th><th>Item</th><th>Telugu</th><th>Full qty</th><th>Unit</th><th/></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.sort_order}</td><td>{i.name}</td><td>{i.name_te}</td><td>{i.full_qty}</td><td>{i.unit}</td><td><button onClick={()=>setEdit({...i})}><Pencil/></button></td></tr>)}</tbody></table></div></section>
 {edit&&<div className="modal-back"><div className="edit-modal"><h2>Edit master item</h2><label>Name<input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Telugu<input value={edit.name_te} onChange={e=>setEdit({...edit,name_te:e.target.value})}/></label><label>Full 12-month quantity<input type="number" step="0.001" value={edit.full_qty} onChange={e=>setEdit({...edit,full_qty:Number(e.target.value)})}/></label><label>Unit<input value={edit.unit} onChange={e=>setEdit({...edit,unit:e.target.value})}/></label><label>Image URL<input value={edit.image||''} onChange={e=>setEdit({...edit,image:e.target.value})}/></label><label>MRP / reference value ₹<input type="number" value={edit.mrp||0} onChange={e=>setEdit({...edit,mrp:Number(e.target.value)})}/></label><label>Reference product page<input type="url" value={edit.source_url||''} onChange={e=>setEdit({...edit,source_url:e.target.value})}/></label><label><input type="checkbox" checked={!!edit.auto_update_image} onChange={e=>setEdit({...edit,auto_update_image:e.target.checked})}/> Auto-update image</label><label><input type="checkbox" checked={!!edit.auto_update_mrp} onChange={e=>setEdit({...edit,auto_update_mrp:e.target.checked})}/> Auto-update MRP</label><div><button onClick={()=>setEdit(null)}>Cancel</button><button className="primary" onClick={save}>Save changes</button></div></div></div>}
 </div>
}
